# D:\city_chain_project\Cargo.toml
[workspace]
members = [
    "global_main_chain",
    "municipal_chain",
    "continental_main_chain"
]
resolver = "2"

[patch.crates-io]
openssl-src = { path = "local_openssl_src" }
