services:
  main_chain:
    build:
      context: ./main_chain
    ports:
      - "8080:8080"
  municipal_chain:
    build:
      context: ./municipal_chain
    ports:
      - "8081:8081"
  dapps:
    build:
      context: ./dapps
    ports:
      - "5000:5000"
    depends_on:
      - main_chain
      - municipal_chain

