version: '3.8'

services:
  dapps:
    build: ./dapps
    ports:
      - "5000:5000"
  municipal_chain:
    build: ./municipal_chain
    ports:
      - "8000:8000"
  continental_main_chain:
    build: ./continental_main_chain
    ports:
      - "8001:8001"
  global_main_chain:
    build: ./global_main_chain
    ports:
      - "8002:8002"

